import Foundation

/// The four language dictionaries, ported verbatim from `src/crt/language.py`,
/// plus English-only keys for the native-only UI (dashboard, video retimer,
/// segments, speedrun.com) — spec §7. Missing translations fall back to
/// English, then to the key itself.
enum LocalizationTables {

    /// The ported keys in `src/crt/language.py` declaration order.
    ///
    /// Swift dictionaries have no stable iteration order, so the reverse lookup
    /// in `Localization.translate` walks this list instead: several keys share
    /// a value (English "Edit (Menu Bar)"/"Edit", French "Add Loads"/"Add Load",
    /// …) and Python — whose dicts are insertion-ordered — always returns the
    /// first-declared match.
    static let orderedKeys: [String] = [
        "Framerate",
        "Start Frame",
        "End Frame",
        "Start Frame (Loads)",
        "End Frame (Loads)",
        "Paste",
        "Paste Start Frame",
        "Paste End Frame",
        "Paste Start Frame (Loads)",
        "Paste End Frame (Loads)",
        "Copy Mod Note",
        "Copy Discord Message",
        "Copy YouTube Chapters",
        "Add Loads",
        "Add Load",
        "Edit Loads",
        "Without Loads",
        "With Loads",
        "Click to Copy Time",
        "File",
        "New Time",
        "Open Time",
        "Session History",
        "Save",
        "Save As",
        "Settings",
        "Exit",
        "Edit (Menu Bar)",
        "Clear Loads",
        "View",
        "Always on Top",
        "Help",
        "About",
        "Edit Load",
        "Save Edits",
        "Discard Changes",
        "Edit",
        "Delete",
        "Loads",
        "File Name",
        "Cancel",
        "CRT Settings",
        "Automatically Check for Updates",
        "Theme",
        "Automatic",
        "Dark",
        "Light",
        "Accent Color",
        "Language",
        "Mod Note Format",
        "Restore Defaults",
        "Apply",
        "Hotkeys",
        "Customize Hotkeys",
        "Press a Key Combination",
        "Reset",
        "Reset All",
        "OK",
        "Duplicate Hotkey",
        "Duplicate Hotkey Message",
    ]

    static let english: [String: String] = [
        "Framerate": "Framerate (FPS)",
        "Start Frame": "Start Frame",
        "End Frame": "End Frame",
        "Start Frame (Loads)": "Start Frame (Loads)",
        "End Frame (Loads)": "End Frame (Loads)",
        "Paste": "Paste",
        "Paste Start Frame": "Paste Start Frame",
        "Paste End Frame": "Paste End Frame",
        "Paste Start Frame (Loads)": "Paste Start Frame (Loads)",
        "Paste End Frame (Loads)": "Paste End Frame (Loads)",
        "Copy Mod Note": "Copy Mod Note",
        "Copy Discord Message": "Copy Discord Message",
        "Copy YouTube Chapters": "Copy YouTube Chapters",
        "Add Loads": "Add Loads",
        "Add Load": "Add Load",
        "Edit Loads": "Edit Loads",
        "Without Loads": "Without Loads",
        "With Loads": "With Loads",
        "Click to Copy Time": "Click to Copy Time",
        "File": "File",
        "New Time": "New Time",
        "Open Time": "Open Time",
        "Session History": "Session History",
        "Save": "Save",
        "Save As": "Save As",
        "Settings": "Settings",
        "Exit": "Exit",
        "Edit (Menu Bar)": "Edit",
        "Clear Loads": "Clear Loads",
        "View": "View",
        "Always on Top": "Always on Top",
        "Help": "Help",
        "About": "About",
        "Edit Load": "Edit Load",
        "Save Edits": "Save Edits",
        "Discard Changes": "Discard Changes",
        "Edit": "Edit",
        "Delete": "Delete",
        "Loads": "Loads",
        "File Name": "File Name",
        "Cancel": "Cancel",
        "CRT Settings": "CRT Settings",
        "Automatically Check for Updates": "Automatically Check for Updates",
        "Theme": "Theme",
        "Automatic": "Automatic",
        "Dark": "Dark",
        "Light": "Light",
        "Accent Color": "Accent Color",
        "Language": "Language",
        "Mod Note Format": "Mod Note Format",
        "Restore Defaults": "Restore Defaults",
        "Apply": "Apply",
        "Hotkeys": "Hotkeys",
        "Customize Hotkeys": "Customize Hotkeys",
        "Press a Key Combination": "Press a key combination",
        "Reset": "Reset",
        "Reset All": "Reset All",
        "OK": "OK",
        "Duplicate Hotkey": "Duplicate Hotkey",
        "Duplicate Hotkey Message": "The same key combination is assigned to more than one action: {names}",

        // ── New keys for the native rewrite (spec §7). English only — every
        // other language falls back to these until translations arrive. Kept
        // in step with `src-windows/CRT.Core/Localization/LanguageCatalog.cs`.
        "Dashboard": "Dashboard",
        "Frame Retimer": "Frame Retimer",
        "Video Retimer": "Video Retimer",
        "Segments": "Segments",
        "Segment": "Segment",
        "Segment Mode": "Segment Mode",
        "Load Mode": "Load Mode",
        "Segment Total": "Segment Total",
        "Full Run": "Full Run",
        "Add Segment": "Add Segment",
        "Segment Start": "Segment Start",
        "Segment End": "Segment End",
        "Clear Segments": "Clear Segments",
        "Toggle Mode": "Toggle Mode",
        "No loads yet": "No loads yet. Add one with the fields on the left.",
        "No segments yet": "No segments yet. Add one with the fields on the left.",
        "Mod note copied": "Mod note copied",
        "Discord message copied": "Discord message copied",
        "YouTube chapters copied": "YouTube chapters copied",
        "Time copied": "Time copied",
        "Copy Time": "Copy Time",
        "Load added successfully.": "Load added successfully.",
        "Segment added successfully.": "Segment added successfully.",
        "Undo": "Undo",
        "Redo": "Redo",
        "Error": "Error",
        "Saved to {path}": "Saved to {path}",
        "Would you like to save the current time first?": "Would you like to save the current time first?",
        "Would you like to save?": "Would you like to save?",
        "Don't Save": "Don't Save",
        "Restore Session": "Restore Session",
        "Restore Session Message": "CRT closed unexpectedly with unsaved changes. Restore the last autosaved session?",
        "Update Available": "A new version ({version}) is available — click to download.",
        "Framerate Mismatch": "Framerate Mismatch",
        "Framerate Mismatch Message": "This video appears to be {detected} FPS, but the session is set to {current} FPS.\n\nUpdate the framerate before calculating the frame?",
        "Woah!": "Woah!",
        "Concerningly Long Load Message": "This load is concerningly long. Would you like to add the load anyway?",
        "Please restart the application to apply the changes.": "Please restart the application to apply the changes.",
        "Restore Defaults Message": "Are you sure you want to restore the default settings?",
        "Yes": "Yes",
        "No": "No",

        // Video retimer
        "Import Video": "Import Video",
        "Local File": "Local File",
        "Local File…": "Local File…",
        "Video URL": "Video URL",
        "YouTube URL": "YouTube URL",
        "Browse": "Browse…",
        "Browse…": "Browse…",
        "Import": "Import",
        "Downloading": "Downloading…",
        "Probing": "Probing…",
        "Play": "Play",
        "Pause": "Pause",
        "Frame Back": "Frame Back",
        "Frame Forward": "Frame Forward",
        "Play/Pause": "Play/Pause",
        "Mark Segment Start": "Mark Segment Start",
        "Mark Segment End": "Mark Segment End",
        "Mark Run Start": "Mark Run Start",
        "Mark Run End": "Mark Run End",
        "Mark Load Start": "Mark Load Start",
        "Mark Load End": "Mark Load End",
        "Current Frame": "Current Frame",
        "Current Time": "Current Time",
        "Export Retimed Video": "Export Retimed Video",
        "Exporting": "Exporting…",
        "Export Complete": "Export Complete",
        "Open": "Open",
        "Show in Folder": "Show in Folder",
        "Tool Needed": "CRT needs {tool} for this feature. Download it now? (~{size})",
        "Download": "Download",
        "Framerate set from video": "Framerate set to {fps} from the video.",
        "No video loaded": "No video loaded. Import a local file, direct URL, or YouTube link above.",

        // Dashboard
        "Run Library": "Run Library",
        "New Retime": "New Retime",
        "Open File": "Open File…",
        "Open File…": "Open File…",
        "Remove from Library": "Remove from Library",
        "Reveal in Finder": "Reveal in Finder",
        "Unsaved Session": "Unsaved Session",
        "Current session (unsaved changes)": "Current session (unsaved changes)",
        "Continue Editing": "Continue Editing",
        "Empty Library": "Runs you open or save appear here.",
        "Modified": "Modified",
        "Start": "Start",
        "End": "End",

        // Speedrun.com
        "Speedrun.com": "Speedrun.com",
        "Sign In": "Sign In",
        "Sign Out": "Sign Out",
        "API Key": "API Key",
        "Get your key": "Get your key",
        "Signed in as {user}": "Signed in as {user}",
        "Sign-in failed": "Sign-in failed. Check the API key and try again.",
        "Runs to Verify": "Runs to Verify",
        "Runs to Verify (n)": "Runs to Verify ({count})",
        "My Recent Runs": "My Recent Runs",
        "Refresh": "Refresh",
        "Watch": "Watch",
        "Retime This": "Retime This",
        "Verify": "Verify",
        "Reject": "Reject",
        "Reject Reason": "Reason",
        "Reason": "Reason",
        "Verify Run Message": "Verify this run?",
        "Reject Run Message": "Reject this run? A reason is required.",
        "Game": "Game",
        "Category": "Category",
        "Player": "Player(s)",
        "Submitted": "Submitted",
        "Claimed Time": "Claimed Time",
        "Video": "Video",
        "Status": "Status",
        "No runs to verify": "No runs awaiting verification. Nice work!",
        "Sign in explainer": "Sign in with your Speedrun.com API key to see runs awaiting verification for the games you moderate.",
        "Loading": "Loading…",
        "Network error": "Couldn't reach Speedrun.com. Check your connection and try again.",

        // Settings (new)
        "Timer Corner": "Timer Corner",
        "Timer Style": "Timer Style",
        "Top Left": "Top Left",
        "Top Right": "Top Right",
        "Bottom Left": "Bottom Left",
        "Bottom Right": "Bottom Right",
        "Pill": "Pill",
        "Plain": "Plain",
        "FFmpeg Path": "FFmpeg Path (empty = auto)",
        "yt-dlp Path": "yt-dlp Path (empty = auto)",
        "Default Mode": "Default Mode",
    ]

    static let french: [String: String] = [
        "Framerate": "Taux de refraichissement",
        "Start Frame": "Première image",
        "End Frame": "Dernière image",
        "Start Frame (Loads)": "Première image (chargement)",
        "End Frame (Loads)": "Dernière image (chargement)",
        "Paste": "Coller",
        "Paste Start Frame": "Coller la première image",
        "Paste End Frame": "Coller la dernière image",
        "Paste Start Frame (Loads)": "Coller la première image (chargement)",
        "Paste End Frame (Loads)": "Coller la dernière image (chargement)",
        "Copy Mod Note": "Copier la note de modérateur",
        "Copy Discord Message": "Copier le message Discord",
        "Copy YouTube Chapters": "Copier les chapitres YouTube",
        "Add Loads": "Ajouter un chargement",
        "Add Load": "Ajouter un chargement",
        "Edit Loads": "Modifier les chargements",
        "Without Loads": "Sans chargements",
        "With Loads": "Avec chargements",
        "Click to Copy Time": "Cliquer pour copier le temps",
        "File": "Fichier",
        "New Time": "Nouveau temps",
        "Open Time": "Ouvrir un temps",
        "Session History": "Historique de session",
        "Save": "Enregister",
        "Save As": "Enregister sous",
        "Settings": "Paramètres",
        "Exit": "Quitter",
        "Edit (Menu Bar)": "Modifier",
        "Clear Loads": "Effacer les chargements",
        "View": "Affichage",
        "Always on Top": "Toujours au premier plan",
        "Help": "Aide",
        "About": "À propos",
        "Edit Load": "Modifier les chargement",
        "Save Edits": "Enregistrer les modifications",
        "Discard Changes": "Annuler les modifications",
        "Edit": "Modifier",
        "Delete": "Supprimer",
        "Loads": "Chargements",
        "File Name": "Nom du fichier",
        "Cancel": "Annuler",
        "CRT Settings": "Paramètres du CRT",
        "Automatically Check for Updates": "Vérifier automatiquement les mises à jours",
        "Theme": "Thème",
        "Automatic": "Automatique",
        "Dark": "Sombre",
        "Light": "Clair",
        "Accent Color": "Couleur d'accent",
        "Language": "Langue",
        "Mod Note Format": "Format de la note de modérateur",
        "Restore Defaults": "Restaurer les paramètres par défaut",
        "Apply": "Appliquer",
        "Hotkeys": "Raccourcis",
        "Customize Hotkeys": "Personnaliser les raccourcis",
        "Press a Key Combination": "Appuyez sur une combinaison de touches",
        "Reset": "Réinitialiser",
        "Reset All": "Tout réinitialiser",
        "OK": "OK",
        "Duplicate Hotkey": "Raccourci en double",
        "Duplicate Hotkey Message": "La même combinaison de touches est assignée à plusieurs actions : {names}",
    ]

    static let polish: [String: String] = [
        "Framerate": "Liczba klatek na sekundę",
        "Start Frame": "Pierwsza klatka",
        "End Frame": "Ostatnia klatka",
        "Start Frame (Loads)": "Pierwsza klatka ładowania",
        "End Frame (Loads)": "Ostatnia klatka ładowania",
        "Paste": "Wklej",
        "Paste Start Frame": "Wklej pierwszą klatkę",
        "Paste End Frame": "Wklej ostatnią klatkę",
        "Paste Start Frame (Loads)": "Wklej pierwszą klatkę ładowania",
        "Paste End Frame (Loads)": "Wklej ostatnią klatkę ładowania",
        "Copy Mod Note": "Skopiuj notatkę moderatora",
        "Copy Discord Message": "Skopiuj wiadomość Discord",
        "Copy YouTube Chapters": "Skopiuj rozdziały YouTube",
        "Add Loads": "Dodaj ładowanie",
        "Add Load": "Dodaj ładowanie",
        "Edit Loads": "Edytuj ładowania",
        "Without Loads": "Bez ładowań",
        "With Loads": "Z ładowaniami",
        "Click to Copy Time": "Kliknij, aby skopiować czas",
        "File": "Plik",
        "New Time": "Nowy czas",
        "Open Time": "Otwórz czas",
        "Session History": "Historia sesji",
        "Save": "Zapisz",
        "Save As": "Zapisz jako",
        "Settings": "Ustawienia",
        "Exit": "Quitter",
        "Edit (Menu Bar)": "Wyjście",
        "Clear Loads": "Wyczyść ładowania",
        "View": "Widok",
        "Always on Top": "Zawsze na wierzchu",
        "Help": "Pomoc",
        "About": "O programie",
        "Edit Load": "Edytuj ładowanie",
        "Save Edits": "Zapisz zmiany",
        "Discard Changes": "Odrzuć zmiany",
        "Edit": "Edytuj",
        "Delete": "Usuń",
        "Loads": "Ładowania",
        "File Name": "Nazwa pliku",
        "Cancel": "Anuluj",
        "CRT Settings": "Ustawienia CRT",
        "Automatically Check for Updates": "Automatycznie sprawdzaj aktualizacje",
        "Theme": "Motyw",
        "Automatic": "Automatyczny",
        "Dark": "Ciemny",
        "Light": "Jasny",
        "Accent Color": "Kolor akcentu",
        "Language": "Język",
        "Mod Note Format": "Format notatki moderatora",
        "Restore Defaults": "Przywróć domyślne",
        "Apply": "Zastosuj",
        "Hotkeys": "Skróty klawiszowe",
        "Customize Hotkeys": "Dostosuj skróty klawiszowe",
        "Press a Key Combination": "Naciśnij kombinację klawiszy",
        "Reset": "Resetuj",
        "Reset All": "Resetuj wszystko",
        "OK": "OK",
        "Duplicate Hotkey": "Zduplikowany skrót",
        "Duplicate Hotkey Message": "Ta sama kombinacja klawiszy jest przypisana do więcej niż jednej akcji: {names}",
    ]

    static let spanish: [String: String] = [
        "Framerate": "Tasa de Fotogramas",
        "Start Frame": "Primer fotograma",
        "End Frame": "Fotograma Finalmente",
        "Start Frame (Loads)": "Primero Fotograma del Carga",
        "End Frame (Loads)": "Fotograma Final del Carga",
        "Paste": "Pegar",
        "Paste Start Frame": "Pegar Primer Fotograma",
        "Paste End Frame": "Pegar Fotograma Final",
        "Paste Start Frame (Loads)": "Pegar Primero Fotograma del Carga",
        "Paste End Frame (Loads)": "Pegar Fotograma Final del Carga",
        "Copy Mod Note": "Copia Nota de Moderador",
        "Copy Discord Message": "Copiar Mensaje de Discord",
        "Copy YouTube Chapters": "Copiar Capítulos de YouTube",
        "Add Loads": "Agregar un Carga",
        "Add Load": "Agregar un Carga",
        "Edit Loads": "Editar los Cargas",
        "Without Loads": "Sin los Loads",
        "With Loads": "Con los Loads",
        "Click to Copy Time": "Copia el Tiempo",
        "File": "Archivo",
        "New Time": "Nuevo Tiempo",
        "Open Time": "Abrir Tiempo",
        "Session History": "Historial de Sesiones",
        "Save": "Guardar",
        "Save As": "Guardar Como",
        "Settings": "Configuraciónes",
        "Exit": "Salir",
        "Edit (Menu Bar)": "Editar",
        "Clear Loads": "Borrar los Loads",
        "View": "Ver",
        "Always on Top": "Siempre Visible",
        "Help": "Ayuda",
        "About": "Sobre",
        "Edit Load": "Editar un Carga",
        "Save Edits": "Guardar Ediciones",
        "Discard Changes": "Borrar los Modificaciónes",
        "Edit": "Editar",
        "Delete": "Borrar",
        "Loads": "Cargas",
        "File Name": "Nombre del Archivo",
        "Cancel": "Cancelar",
        "CRT Settings": "Configuraciónes de CRT",
        "Automatically Check for Updates": "Buscar Actualizaciones Automáticamente",
        "Theme": "Tema",
        "Automatic": "Automático",
        "Dark": "Oscuro",
        "Light": "Claro",
        "Accent Color": "Color de Acento",
        "Language": "Idioma",
        "Mod Note Format": "Formato de la Nota de Moderador",
        "Restore Defaults": "Restaurar Valores Predeterminados",
        "Apply": "Aplicar",
        "Hotkeys": "Atajos de Teclado",
        "Customize Hotkeys": "Personalizar Atajos de Teclado",
        "Press a Key Combination": "Presiona una combinación de teclas",
        "Reset": "Restablecer",
        "Reset All": "Restablecer Todo",
        "OK": "OK",
        "Duplicate Hotkey": "Atajo Duplicado",
        "Duplicate Hotkey Message": "La misma combinación de teclas está asignada a más de una acción: {names}",
    ]
}
